/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author mikel
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public LOGIN() {
        initComponents();
    }

       private Color hoverColor = new Color(180, 180, 180); // Grayish color on hover
       private Color defaultColor = new Color(255, 255, 255); // Default white color


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        System_Name = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        unf = new javax.swing.JTextField();
        sps = new javax.swing.JCheckBox();
        psf = new javax.swing.JPasswordField();
        new_user = new javax.swing.JLabel();
        register = new javax.swing.JLabel();
        Balbz_logo = new javax.swing.JLabel();
        Event_icon = new javax.swing.JLabel();
        Register = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        Exit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOGIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        System_Name.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 20)); // NOI18N
        System_Name.setForeground(new java.awt.Color(250, 249, 190));
        System_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        System_Name.setText("Event Photography Booking System");
        LOGIN.add(System_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 440, 40));

        user.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 240));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Username");
        LOGIN.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 249, -1, 30));

        unf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        unf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfActionPerformed(evt);
            }
        });
        LOGIN.add(unf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 240, 40));

        sps.setBackground(new java.awt.Color(255, 255, 255));
        sps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spsMouseClicked(evt);
            }
        });
        sps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spsActionPerformed(evt);
            }
        });
        LOGIN.add(sps, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 40, 20));

        psf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        psf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        LOGIN.add(psf, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 240, 40));

        new_user.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        new_user.setForeground(new java.awt.Color(255, 255, 255));
        new_user.setText("New User? ");
        new_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_userMouseClicked(evt);
            }
        });
        LOGIN.add(new_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 80, 30));

        register.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        register.setForeground(new java.awt.Color(255, 255, 0));
        register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        register.setText("Click here to Register");
        register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerMouseClicked(evt);
            }
        });
        LOGIN.add(register, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 430, 150, 30));

        Balbz_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logo1.png"))); // NOI18N
        LOGIN.add(Balbz_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        Event_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Event_in.png"))); // NOI18N
        Event_icon.setText("jLabel2");
        LOGIN.add(Event_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 70));

        Register.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 240));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("Password");
        LOGIN.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 339, -1, 30));

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LOGIN.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 380, 60, 30));

        exit.setBackground(new java.awt.Color(240, 240, 190));
        exit.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit);
        Exit.setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        LOGIN.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 60, 30));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/G1.png"))); // NOI18N
        LOGIN.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unfActionPerformed

    private void spsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spsActionPerformed

    private void spsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spsMouseClicked
        if (sps.isSelected()) {
            psf.setEchoChar((char) 0);  // Show password
        } else {
            psf.setEchoChar('*');  // Hide password
        }    }//GEN-LAST:event_spsMouseClicked

    private void new_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_userMouseClicked
       

    }//GEN-LAST:event_new_userMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
      String username = unf.getText();
      String password = new String(psf.getPassword());

    if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Fields cannot be empty!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (username.equals("admin") && password.equals("pass123")) {
        JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        // Open the Dashboard panel
        DASHBOARD dashboard = new DASHBOARD();
        dashboard.setVisible(true);
        
        // Close the current login window
        this.dispose();
    } else {
        JOptionPane.showMessageDialog(this, "Invalid username or password", "Login Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
         login.setBackground(defaultColor); 
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
         login.setOpaque(true); // Ensure background change is visible
         login.setBackground(hoverColor);    }//GEN-LAST:event_loginMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
         exit.setBackground(defaultColor); 
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
         exit.setOpaque(true); // Ensure background change is visible
         exit.setBackground(hoverColor);         
     }//GEN-LAST:event_exitMouseExited

    private void registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerMouseClicked
        REGISTRATION reg = new REGISTRATION();
        reg.setVisible(true);    }//GEN-LAST:event_registerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel Balbz_logo;
    private javax.swing.JLabel Event_icon;
    private javax.swing.JPanel Exit;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel System_Name;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login;
    private javax.swing.JLabel new_user;
    private javax.swing.JPasswordField psf;
    private javax.swing.JLabel register;
    private javax.swing.JCheckBox sps;
    private javax.swing.JTextField unf;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
