/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import javax.swing.JOptionPane;
import ADMINISTRATION.ADMIN_PANEL;
import STAFF.STAFF_PANEL;
import config.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;


/**
 *
 * @author mikel
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public LOGIN() {
        initComponents();
    }

       private Color hoverColor = new Color(180, 180, 180); // Grayish color on hover
       private Color defaultColor = new Color(255, 255, 255); // Default white color


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        System_Name = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        unf = new javax.swing.JTextField();
        sps = new javax.swing.JCheckBox();
        psf = new javax.swing.JPasswordField();
        role = new javax.swing.JComboBox<>();
        acc_type = new javax.swing.JLabel();
        Click = new javax.swing.JLabel();
        new_user = new javax.swing.JLabel();
        Balbz_logo = new javax.swing.JLabel();
        Event_icon = new javax.swing.JLabel();
        Register = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        Exit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOGIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        System_Name.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 22)); // NOI18N
        System_Name.setForeground(new java.awt.Color(250, 249, 190));
        System_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        System_Name.setText("System");
        LOGIN.add(System_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 40));

        Name.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 22)); // NOI18N
        Name.setForeground(new java.awt.Color(250, 249, 190));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Event Photography Booking ");
        LOGIN.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 40));

        user.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(255, 255, 240));
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Username");
        LOGIN.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 800, 30));

        unf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        unf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        unf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfActionPerformed(evt);
            }
        });
        LOGIN.add(unf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 220, 30));

        sps.setBackground(new java.awt.Color(255, 255, 255));
        sps.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sps.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                spsMouseClicked(evt);
            }
        });
        sps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spsActionPerformed(evt);
            }
        });
        LOGIN.add(sps, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 30, 30));

        psf.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        psf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        psf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psfActionPerformed(evt);
            }
        });
        LOGIN.add(psf, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 220, 30));

        role.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        LOGIN.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 340, 100, -1));

        acc_type.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        acc_type.setForeground(new java.awt.Color(255, 255, 240));
        acc_type.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        acc_type.setText("Role");
        LOGIN.add(acc_type, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 370, 100, 20));

        Click.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        Click.setForeground(new java.awt.Color(255, 255, 0));
        Click.setText("Click here to register");
        Click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickMouseClicked(evt);
            }
        });
        LOGIN.add(Click, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 150, 30));

        new_user.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        new_user.setForeground(new java.awt.Color(255, 255, 255));
        new_user.setText("New User? ");
        new_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_userMouseClicked(evt);
            }
        });
        LOGIN.add(new_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 80, 30));

        Balbz_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logo1.png"))); // NOI18N
        LOGIN.add(Balbz_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        Event_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Event_in.png"))); // NOI18N
        Event_icon.setText("jLabel2");
        LOGIN.add(Event_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 70));

        Register.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 240));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("Password");
        LOGIN.add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, 300, 800, 30));

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        LOGIN.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 60, 20));

        exit.setBackground(new java.awt.Color(240, 240, 190));
        exit.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit);
        Exit.setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        LOGIN.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 20));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/G1.png"))); // NOI18N
        LOGIN.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unfActionPerformed

    private void spsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spsActionPerformed

    private void spsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_spsMouseClicked
        if (sps.isSelected()) {
            psf.setEchoChar((char) 0);  // Show password
        } else {
            psf.setEchoChar('*');  // Hide password
        }    }//GEN-LAST:event_spsMouseClicked

    private void new_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_userMouseClicked
       

    }//GEN-LAST:event_new_userMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
        
        String username = unf.getText();
        String password = new String(psf.getPassword());
        String acc = role.getSelectedItem().toString();

        if (username == null || username.trim().isEmpty() || password == null || password.trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username and password cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; // Exit early
        }

        connectDB con = new connectDB();
        Connection cn = con.getConnection(); // Get database connection

        String sql = "SELECT password, role FROM user WHERE username = ?";

        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, username); // Set username parameter
            ResultSet rs = pst.executeQuery();

            if (rs.next()) { // If user exists
                String storedPassword = rs.getString("password");
                String roleFromDB = rs.getString("role");

                // **Check if password matches**
                if (storedPassword.equals(password)) {  

                    // **Check if role matches the selected role**
                    if (roleFromDB.equalsIgnoreCase(acc)) {  
                        JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

                        // **Role-based redirection**
                        if ("Admin".equalsIgnoreCase(roleFromDB)) {
                            ADMIN_PANEL admin = new ADMIN_PANEL();
                            admin.setVisible(true);
                            this.dispose();
                        } else if ("Staff".equalsIgnoreCase(roleFromDB)) {
                            STAFF_PANEL staff = new STAFF_PANEL();
                            staff.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid role!", "Login Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect role selection!", "Login Error", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect password.", "Login Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Username not found.", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

            // Close resources
            rs.close();
            pst.close();
            cn.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
         login.setBackground(defaultColor); 
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
         login.setOpaque(true); // Ensure background change is visible
         login.setBackground(hoverColor);    }//GEN-LAST:event_loginMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
         exit.setBackground(defaultColor); 
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
         exit.setOpaque(true); // Ensure background change is visible
         exit.setBackground(hoverColor);         
     }//GEN-LAST:event_exitMouseExited

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed

    }//GEN-LAST:event_roleActionPerformed

    private void psfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psfActionPerformed

    private void ClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickMouseClicked
       REGISTRATION reg = new REGISTRATION();
       reg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ClickMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel Balbz_logo;
    private javax.swing.JLabel Click;
    private javax.swing.JLabel Event_icon;
    private javax.swing.JPanel Exit;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel System_Name;
    private javax.swing.JLabel acc_type;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login;
    private javax.swing.JLabel new_user;
    private javax.swing.JPasswordField psf;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JCheckBox sps;
    private javax.swing.JTextField unf;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
