/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CRUD;

import CONFIG.Util;
import CONFIG.connectDB;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JDesktopPane;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import javax.swing.border.EmptyBorder;
import javax.swing.border.TitledBorder;

/**
 *
 * @author mikel
 */
public class Add_photograph extends javax.swing.JPanel {

    /**
     * Creates new form Add_user
     */
    public Add_photograph() {
        initComponents();
        
        
        
        fnfield.setBackground(new java.awt.Color(0,0,0,1));
        lnfield.setBackground(new java.awt.Color(0,0,0,1));
        efield.setBackground(new java.awt.Color(0,0,0,1));
        pfield.setBackground(new java.awt.Color(0,0,0,1));
        exfield.setBackground(new java.awt.Color(0,0,0,1));
    }
    
    
         
    private static void centerJPanel(JDesktopPane desktopPane, JPanel panel) {
       int x = (desktopPane.getWidth() - panel.getWidth()) / 2;
       int y = (desktopPane.getHeight() - panel.getHeight()) / 2;
       panel.setLocation(x, y);
   }



     private void displayError(JLabel field, String message) {
            field.setText(message);
            field.setForeground(new Color(255, 105, 97));
        }
        
      public void setTitledBorder(JComponent component, String title, Color color) {
        TitledBorder titledBorder = BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(color, 1),  // Use given color
            title,  
            TitledBorder.LEFT,  
            TitledBorder.TOP,  
            new Font("Franklin Gothic Medium", Font.PLAIN, 16),  
            color  // Title text color
        );

        component.setBorder(BorderFactory.createCompoundBorder(titledBorder, new EmptyBorder(0, 5, 0, 0)));

        // Make text field background fully transparent
        if (component instanceof JTextField) {
            JTextField textField = (JTextField) component;
            textField.setOpaque(false); // Remove background fill
            textField.setBackground(new Color(0, 0, 0, 0)); // Ensure full transparency
            textField.setCaretColor(Color.WHITE); // Ensure cursor is visible
            textField.setForeground(Color.decode("#F5E196"));
    }
      }

    public void setInvalidTitledBorder(JComponent component, String title) {
        TitledBorder titledBorder = BorderFactory.createTitledBorder(
            BorderFactory.createLineBorder(new Color(255, 105, 97)),  // Red border for invalid input
            title,
            TitledBorder.LEFT,
            TitledBorder.TOP,
            new Font("Franklin Gothic Medium", Font.PLAIN, 16),
            new Color(255, 105, 97) // Red text color for the title
        );

        component.setBorder(BorderFactory.createCompoundBorder(titledBorder, new EmptyBorder(0, 5, 0, 0)));

        // Make text field background fully transparent
        if (component instanceof JTextField) {
            JTextField textField = (JTextField) component;
            textField.setOpaque(false); 
            textField.setBackground(new Color(0, 0, 0, 0)); 
            textField.setCaretColor(Color.WHITE); // Make sure cursor is visible
            textField.setForeground(new Color(255, 105, 97));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rfield = new javax.swing.JTextField();
        username_error2 = new javax.swing.JLabel();
        expfield = new javax.swing.JTextField();
        username_error1 = new javax.swing.JLabel();
        details = new javax.swing.JLabel();
        fnfield = new javax.swing.JTextField();
        lnfield = new javax.swing.JTextField();
        efield = new javax.swing.JTextField();
        pfield = new javax.swing.JTextField();
        exfield = new javax.swing.JTextField();
        name_error = new javax.swing.JLabel();
        contact_error = new javax.swing.JLabel();
        lname_error = new javax.swing.JLabel();
        email_error = new javax.swing.JLabel();
        username_error = new javax.swing.JLabel();
        user_icon = new javax.swing.JLabel();
        createpass_error = new javax.swing.JLabel();
        cancel = new javax.swing.JPanel();
        ca1 = new javax.swing.JLabel();
        add = new javax.swing.JPanel();
        a = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        rfield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        rfield.setForeground(new java.awt.Color(153, 153, 153));
        rfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Rate", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        rfield.setCaretColor(new java.awt.Color(240, 240, 240));
        rfield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        rfield.setOpaque(false);
        rfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rfieldFocusLost(evt);
            }
        });
        rfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfieldActionPerformed(evt);
            }
        });
        jPanel1.add(rfield);
        rfield.setBounds(320, 190, 260, 60);

        username_error2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        username_error2.setForeground(new java.awt.Color(255, 102, 102));
        username_error2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(username_error2);
        username_error2.setBounds(320, 250, 260, 20);

        expfield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        expfield.setForeground(new java.awt.Color(153, 153, 153));
        expfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Experience", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        expfield.setCaretColor(new java.awt.Color(240, 240, 240));
        expfield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        expfield.setOpaque(false);
        expfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                expfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                expfieldFocusLost(evt);
            }
        });
        expfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expfieldActionPerformed(evt);
            }
        });
        jPanel1.add(expfield);
        expfield.setBounds(320, 110, 260, 60);

        username_error1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        username_error1.setForeground(new java.awt.Color(255, 102, 102));
        username_error1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(username_error1);
        username_error1.setBounds(320, 170, 260, 20);

        details.setBackground(new java.awt.Color(0, 0, 0));
        details.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 20)); // NOI18N
        details.setForeground(new java.awt.Color(255, 255, 240));
        details.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        details.setText("ADD PHOTOGRAPHER");
        jPanel1.add(details);
        details.setBounds(0, 30, 600, 40);

        fnfield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        fnfield.setForeground(new java.awt.Color(153, 153, 153));
        fnfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "First Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        fnfield.setCaretColor(new java.awt.Color(240, 240, 240));
        fnfield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        fnfield.setOpaque(false);
        fnfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                fnfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                fnfieldFocusLost(evt);
            }
        });
        fnfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnfieldActionPerformed(evt);
            }
        });
        jPanel1.add(fnfield);
        fnfield.setBounds(40, 110, 260, 60);

        lnfield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        lnfield.setForeground(new java.awt.Color(153, 153, 153));
        lnfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Last Name", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        lnfield.setCaretColor(new java.awt.Color(240, 240, 240));
        lnfield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        lnfield.setOpaque(false);
        lnfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lnfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                lnfieldFocusLost(evt);
            }
        });
        lnfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnfieldActionPerformed(evt);
            }
        });
        jPanel1.add(lnfield);
        lnfield.setBounds(40, 190, 260, 60);

        efield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        efield.setForeground(new java.awt.Color(153, 153, 153));
        efield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Email", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        efield.setCaretColor(new java.awt.Color(240, 240, 240));
        efield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        efield.setOpaque(false);
        efield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                efieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                efieldFocusLost(evt);
            }
        });
        efield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                efieldActionPerformed(evt);
            }
        });
        jPanel1.add(efield);
        efield.setBounds(40, 270, 260, 60);

        pfield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        pfield.setForeground(new java.awt.Color(153, 153, 153));
        pfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Phone Number", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        pfield.setCaretColor(new java.awt.Color(240, 240, 240));
        pfield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        pfield.setOpaque(false);
        pfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                pfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                pfieldFocusLost(evt);
            }
        });
        pfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pfieldActionPerformed(evt);
            }
        });
        jPanel1.add(pfield);
        pfield.setBounds(40, 350, 260, 60);

        exfield.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        exfield.setForeground(new java.awt.Color(153, 153, 153));
        exfield.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Expertise", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Franklin Gothic Medium", 0, 16), new java.awt.Color(240, 240, 240))); // NOI18N
        exfield.setCaretColor(new java.awt.Color(240, 240, 240));
        exfield.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        exfield.setOpaque(false);
        exfield.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                exfieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                exfieldFocusLost(evt);
            }
        });
        exfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exfieldActionPerformed(evt);
            }
        });
        jPanel1.add(exfield);
        exfield.setBounds(40, 430, 260, 60);

        name_error.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        name_error.setForeground(new java.awt.Color(255, 102, 102));
        name_error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(name_error);
        name_error.setBounds(40, 170, 260, 20);

        contact_error.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        contact_error.setForeground(new java.awt.Color(255, 102, 102));
        contact_error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(contact_error);
        contact_error.setBounds(40, 410, 260, 20);

        lname_error.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        lname_error.setForeground(new java.awt.Color(255, 102, 102));
        lname_error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lname_error);
        lname_error.setBounds(40, 250, 260, 20);

        email_error.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        email_error.setForeground(new java.awt.Color(255, 102, 102));
        email_error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(email_error);
        email_error.setBounds(40, 330, 260, 20);

        username_error.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        username_error.setForeground(new java.awt.Color(255, 102, 102));
        username_error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(username_error);
        username_error.setBounds(40, 490, 260, 20);

        user_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/setting.png"))); // NOI18N
        jPanel1.add(user_icon);
        user_icon.setBounds(390, 90, 40, 40);

        createpass_error.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 13)); // NOI18N
        createpass_error.setForeground(new java.awt.Color(255, 102, 102));
        createpass_error.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(createpass_error);
        createpass_error.setBounds(70, 540, 260, 20);

        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cancelMouseExited(evt);
            }
        });
        cancel.setLayout(new java.awt.BorderLayout());

        ca1.setBackground(new java.awt.Color(0, 0, 0));
        ca1.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        ca1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ca1.setText("Cancel");
        ca1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ca1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ca1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ca1MouseExited(evt);
            }
        });
        cancel.add(ca1, java.awt.BorderLayout.CENTER);

        jPanel1.add(cancel);
        cancel.setBounds(40, 570, 80, 30);

        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.setLayout(new java.awt.BorderLayout());

        a.setBackground(new java.awt.Color(0, 0, 0));
        a.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        a.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        a.setText("Add");
        a.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aMouseExited(evt);
            }
        });
        add.add(a, java.awt.BorderLayout.CENTER);

        jPanel1.add(add);
        add.setBounds(490, 570, 80, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ca1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ca1MouseClicked

    private void ca1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ca1MouseEntered

    private void ca1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ca1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ca1MouseExited

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelMouseClicked

    private void cancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseEntered
       cancel.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_cancelMouseEntered

    private void cancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseExited
       cancel.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_cancelMouseExited

    private void aMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_aMouseClicked

    private void aMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseEntered
        a.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_aMouseEntered

    private void aMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aMouseExited
       a.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_aMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseClicked

    private void addMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseEntered

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_addMouseExited

    private void exfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exfieldActionPerformed

    private void exfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_exfieldFocusLost
        displayError(username_error, "");
        setTitledBorder(exfield, "Username", Color.WHITE);
        exfield.setForeground(Color.WHITE);
    }//GEN-LAST:event_exfieldFocusLost

    private void exfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_exfieldFocusGained
        exfield.setForeground(Color.WHITE);
        setTitledBorder(exfield, "Username", Color.decode("#F5E196"));
    }//GEN-LAST:event_exfieldFocusGained

    private void pfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pfieldActionPerformed

    private void pfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldFocusLost
        displayError(contact_error, "");
        setTitledBorder(pfield, "Phone Number", Color.WHITE);
        pfield.setForeground(Color.WHITE);
    }//GEN-LAST:event_pfieldFocusLost

    private void pfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_pfieldFocusGained
        pfield.setForeground(Color.WHITE);
        setTitledBorder(pfield, "Phone Number", Color.decode("#F5E196"));
    }//GEN-LAST:event_pfieldFocusGained

    private void efieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_efieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_efieldActionPerformed

    private void efieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_efieldFocusLost
        displayError(email_error, "");
        setTitledBorder(efield, "Email", Color.WHITE);
        efield.setForeground(Color.WHITE);
    }//GEN-LAST:event_efieldFocusLost

    private void efieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_efieldFocusGained
        efield.setForeground(Color.WHITE);
        setTitledBorder(efield, "Email", Color.decode("#F5E196"));
    }//GEN-LAST:event_efieldFocusGained

    private void lnfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnfieldActionPerformed

    private void lnfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnfieldFocusLost
        setTitledBorder(lnfield, "Last Name", Color.WHITE);
        lnfield.setForeground(Color.WHITE);
        displayError(lname_error, "");
    }//GEN-LAST:event_lnfieldFocusLost

    private void lnfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lnfieldFocusGained
        lnfield.setForeground(Color.WHITE);
        setTitledBorder(lnfield, "Last Name", Color.decode("#F5E196"));
    }//GEN-LAST:event_lnfieldFocusGained

    private void fnfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnfieldActionPerformed

    }//GEN-LAST:event_fnfieldActionPerformed

    private void fnfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnfieldFocusLost
        displayError(name_error, "");
        setTitledBorder(fnfield, "First Name", Color.WHITE);
        fnfield.setForeground(Color.WHITE);
    }//GEN-LAST:event_fnfieldFocusLost

    private void fnfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fnfieldFocusGained
        fnfield.setForeground(Color.WHITE);
        setTitledBorder(fnfield, "First Name", Color.decode("#F5E196"));
    }//GEN-LAST:event_fnfieldFocusGained

    private void expfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_expfieldFocusGained

    private void expfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_expfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_expfieldFocusLost

    private void expfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expfieldActionPerformed

    private void rfieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rfieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_rfieldFocusGained

    private void rfieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rfieldFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_rfieldFocusLost

    private void rfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfieldActionPerformed

    
    boolean pass_visible = false;
    
    private boolean isEmailValid(String email) {
        String emailRegex = "^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$";
        return email.matches(emailRegex);
    }
    
    private boolean isPhoneNumberValid(String phoneNumber) {
        String phoneRegex = "^(\\+63|0)9\\d{9}$";
        return phoneNumber.matches(phoneRegex);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JPanel add;
    private javax.swing.JLabel ca1;
    private javax.swing.JPanel cancel;
    private javax.swing.JLabel contact_error;
    private javax.swing.JLabel createpass_error;
    private javax.swing.JLabel details;
    public javax.swing.JTextField efield;
    private javax.swing.JLabel email_error;
    public javax.swing.JTextField exfield;
    public javax.swing.JTextField expfield;
    public javax.swing.JTextField fnfield;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lname_error;
    public javax.swing.JTextField lnfield;
    private javax.swing.JLabel name_error;
    public javax.swing.JTextField pfield;
    public javax.swing.JTextField rfield;
    private javax.swing.JLabel user_icon;
    private javax.swing.JLabel username_error;
    private javax.swing.JLabel username_error1;
    private javax.swing.JLabel username_error2;
    // End of variables declaration//GEN-END:variables

  
}
