/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AUTHENTICATION;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import ADMINISTRATOR.ADMIN_PANEL;
import STAFF.STAFF_PANEL;
import CONFIG.connectDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;


/**
 *
 * @author mikel
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public LOGIN() {
        initComponents();
    }
    
  

       private Color hoverColor = new Color(180, 180, 180); // Grayish color on hover
       private Color defaultColor = new Color(255, 255, 255); // Default white color


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        LOGIN = new javax.swing.JPanel();
        Name = new javax.swing.JLabel();
        System_Name = new javax.swing.JLabel();
        unf = new javax.swing.JTextField();
        u_icon = new javax.swing.JLabel();
        show_pass = new javax.swing.JLabel();
        psf = new javax.swing.JPasswordField();
        p_icon = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        r_icon = new javax.swing.JLabel();
        new_user = new javax.swing.JLabel();
        Balbz_logo = new javax.swing.JLabel();
        Event_icon = new javax.swing.JLabel();
        Click = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        Exit = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        BG1 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LOGIN.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 22)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 153));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name.setText("Event Photography Booking ");
        LOGIN.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 800, 40));

        System_Name.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 22)); // NOI18N
        System_Name.setForeground(new java.awt.Color(255, 255, 153));
        System_Name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        System_Name.setText("System");
        LOGIN.add(System_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 800, 40));

        unf.setBackground(new java.awt.Color(255, 255, 250));
        unf.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        unf.setForeground(new java.awt.Color(153, 153, 153));
        unf.setText(" Enter username...");
        unf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        unf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                unfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                unfFocusLost(evt);
            }
        });
        unf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unfActionPerformed(evt);
            }
        });
        LOGIN.add(unf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 220, 30));

        u_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        u_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/user.png"))); // NOI18N
        LOGIN.add(u_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 30, 30));

        show_pass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/hidden.png"))); // NOI18N
        show_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                show_passMouseClicked(evt);
            }
        });
        LOGIN.add(show_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 30, 30));

        psf.setBackground(new java.awt.Color(255, 255, 250));
        psf.setFont(new java.awt.Font("Franklin Gothic Medium", 2, 16)); // NOI18N
        psf.setForeground(new java.awt.Color(153, 153, 153));
        psf.setText(" Enter password...");
        psf.setEchoChar('\u0000');
        psf.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                psfFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                psfFocusLost(evt);
            }
        });
        psf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psfActionPerformed(evt);
            }
        });
        LOGIN.add(psf, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 220, 30));

        p_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/padlock.png"))); // NOI18N
        LOGIN.add(p_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 30, 30));

        role.setBackground(new java.awt.Color(255, 255, 250));
        role.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        role.setForeground(new java.awt.Color(153, 153, 153));
        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));
        role.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roleActionPerformed(evt);
            }
        });
        LOGIN.add(role, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 100, 30));

        r_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        r_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PHOTOS/setting.png"))); // NOI18N
        LOGIN.add(r_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 40, 30));

        new_user.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        new_user.setForeground(new java.awt.Color(255, 255, 255));
        new_user.setText("New User? ");
        new_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                new_userMouseClicked(evt);
            }
        });
        LOGIN.add(new_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 80, 30));

        Balbz_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/logo1.png"))); // NOI18N
        LOGIN.add(Balbz_logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, -1, -1));

        Event_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Event_in.png"))); // NOI18N
        Event_icon.setText("jLabel2");
        LOGIN.add(Event_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 70, 70));

        Click.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 15)); // NOI18N
        Click.setForeground(new java.awt.Color(255, 255, 0));
        Click.setText("Click here to register");
        Click.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClickMouseExited(evt);
            }
        });
        LOGIN.add(Click, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 150, 30));

        login.setBackground(new java.awt.Color(153, 153, 153));
        login.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login.setText("Login");
        login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginMouseExited(evt);
            }
        });

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        LOGIN.add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 60, 20));

        exit.setBackground(new java.awt.Color(240, 240, 190));
        exit.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 16)); // NOI18N
        exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ExitLayout = new javax.swing.GroupLayout(Exit);
        Exit.setLayout(ExitLayout);
        ExitLayout.setHorizontalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        ExitLayout.setVerticalGroup(
            ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ExitLayout.createSequentialGroup()
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        LOGIN.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 60, 20));

        BG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/G1.png"))); // NOI18N
        BG1.setAutoscrolls(true);
        LOGIN.add(BG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LOGIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void new_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_new_userMouseClicked
       

    }//GEN-LAST:event_new_userMouseClicked

    private void loginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseClicked
      
        String acc = role.getSelectedItem().toString();
        String username = unf.getText().trim();
        String password = new String(psf.getPassword()).trim();

      
        // Check for empty fields
        if (username.isEmpty() || password.isEmpty()) {
            if (username.isEmpty()) {
                unf.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            }
            if (password.isEmpty()) {
                psf.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
            }

            JOptionPane.showMessageDialog(null, "Username and password cannot be empty.", "Validation Error", JOptionPane.WARNING_MESSAGE);
            return; // Exit early
        }



        connectDB con = new connectDB();
        Connection cn = con.getConnection(); // Get database connection

        String sql = "SELECT password, role, status FROM user WHERE username = ?";

        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            pst.setString(1, username); // Set username parameter
            ResultSet rs = pst.executeQuery();

            if (rs.next()) { // If user exists
                String storedPassword = rs.getString("password");
                String roleFromDB = rs.getString("role");
                String stat = rs.getString("status");

                // **Check if password matches**
                if (storedPassword.equals(password)) {  

                    if("Inactive".equalsIgnoreCase(stat)){
                        JOptionPane.showMessageDialog(this, "Your account is not active yet. Contact admin", "Login Error", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else if (roleFromDB.equalsIgnoreCase(acc)) {  
                        JOptionPane.showMessageDialog(this, "Login successful!", "Success", JOptionPane.INFORMATION_MESSAGE);

                     
                        // **Role-based redirection**
                        if ("Admin".equalsIgnoreCase(roleFromDB)) {
                            ADMIN_PANEL admin = new ADMIN_PANEL();
                            admin.setVisible(true);
                            this.dispose();
                        } else if ("Staff".equalsIgnoreCase(roleFromDB)) {
                            STAFF_PANEL staff = new STAFF_PANEL();
                            staff.setVisible(true);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Invalid role!", "Login Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "Incorrect role selection!", "Login Error", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect password.", "Login Error", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Username and password is incorrect. Try again!", "Login Error", JOptionPane.ERROR_MESSAGE);
            }

            // Close resources
            rs.close();
            pst.close();
            cn.close();

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(null, "Database error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_loginMouseClicked

    private void loginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseEntered
         login.setBackground(defaultColor); 
    }//GEN-LAST:event_loginMouseEntered

    private void loginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginMouseExited
         login.setOpaque(true); // Ensure background change is visible
         login.setBackground(hoverColor);    }//GEN-LAST:event_loginMouseExited

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMouseClicked

    private void exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseEntered
         exit.setBackground(defaultColor); 
    }//GEN-LAST:event_exitMouseEntered

    private void exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseExited
         exit.setOpaque(true); // Ensure background change is visible
         exit.setBackground(hoverColor);         
     }//GEN-LAST:event_exitMouseExited

    private void roleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roleActionPerformed

    }//GEN-LAST:event_roleActionPerformed

    private void psfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_psfActionPerformed

    private void ClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickMouseClicked
       REGISTRATION reg = new REGISTRATION();
       reg.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ClickMouseClicked

    private void ClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickMouseEntered
       Click.setForeground(new Color(231,231,198));
    }//GEN-LAST:event_ClickMouseEntered

    private void psfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psfFocusGained
        if (new String(psf.getPassword()).equals(" Enter password...")) {
            psf.setText("");
            psf.setEchoChar('•'); // Mask password
            psf.setForeground(Color.BLACK);           
            psf.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));

        }
    }//GEN-LAST:event_psfFocusGained

    private void psfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_psfFocusLost
        if (new String(psf.getPassword()).isEmpty()) {
            psf.setText(" Enter password...");
            psf.setEchoChar((char) 0); // Show text instead of masked chars
            psf.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_psfFocusLost

    private void unfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unfActionPerformed

    private void unfFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unfFocusGained
        if(unf.getText().equals(" Enter username...")){
            unf.setText("");
            unf.setForeground(Color.BLACK);
            unf.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));

        }
    }//GEN-LAST:event_unfFocusGained

    private void unfFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_unfFocusLost
        if(unf.getText().isEmpty()){
            unf.setText(" Enter username...");
            unf.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_unfFocusLost

    private void ClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClickMouseExited
        Click.setForeground(new Color(255,255,0));
    }//GEN-LAST:event_ClickMouseExited

    
    private boolean pass_visible = false;
    private void show_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_show_passMouseClicked
        
        pass_visible = !pass_visible;
        String currentText = psf.getText().trim();

        if (pass_visible) {
            if (!currentText.equals(" Enter password...")) {
                psf.setEchoChar((char) 0);
            }
            show_pass.setIcon(new ImageIcon(getClass().getResource("/PHOTOS/view.png")));
        } else {
            if (!currentText.equals(" Enter password...")) {
                psf.setEchoChar('•');
            }
            show_pass.setIcon(new ImageIcon(getClass().getResource("/PHOTOS/hidden.png")));
        }
     

    }//GEN-LAST:event_show_passMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG1;
    private javax.swing.JLabel Balbz_logo;
    private javax.swing.JLabel Click;
    private javax.swing.JLabel Event_icon;
    private javax.swing.JPanel Exit;
    private javax.swing.JPanel LOGIN;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel System_Name;
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel login;
    private javax.swing.JLabel new_user;
    private javax.swing.JLabel p_icon;
    private javax.swing.JPasswordField psf;
    private javax.swing.JLabel r_icon;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JLabel show_pass;
    private javax.swing.JLabel u_icon;
    private javax.swing.JTextField unf;
    // End of variables declaration//GEN-END:variables
}
